- name: git clone asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    version: "{{ version }}"
    dest: "{{ [ansible_env.HOME, '.asdf' ] | join('/') }}"

- name: asdf init
  blockinfile:
    path: "{{ item.path }}"
    create: yes
    insertafter: EOF
    marker: "# {mark} asdf init."
    block: |
      . $HOME/.asdf/asdf.sh
      . $HOME/.asdf/completions/asdf.bash
  with_items:
    - { path: "~/.zsh.d/09-asdf.sh" }
