- name: install asdf plugin
  shell:
    cmd: |
      asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git

- name: install nodejs
  shell:
    cmd: |
      asdf install nodejs {{ version }}

- name: set npm global dir.
  shell:
    cmd: |
      mkdir -p ~/.npm-global/bin
      npm config set prefix ~/.npm-global

- name: add ~/.npm-global/bin to $PATH
  blockinfile:
    path: "~/.bash_profile"
    create: yes
    insertafter: EOF
    marker: "# {mark} nodejs"
    block: |
      export PATH=${PATH}:~/.npm-global/bin/

