- name: install dependency packages
  become: true
  apt:
    name:
     - libcurl4-gnutls-dev
     - libexpat1-dev
     - gettext
     - libssl-dev
     - zlib1g-dev
     - build-essential
     - gcc
     - autoconf
     - curl
    state: present

- name: download git
  become: true
  get_url:
    url=https://github.com/git/git/archive/master.zip
    dest=/tmp/git-master.zip
  register: git_zip

- name: check existing git-master.zip
  stat: path={{ git_zip.dest }}
  register: git_zip_stat

#- name: check if git installation is required
#  set_fact:
#    need_to_install: "{{ git_zip_stat.stat.exists == True
#                        and git_installed_version.rc != 0 }}"

- name: install git
  become: true
  shell:
    cmd: |
      cd /tmp
      rm -rf git-master
      unzip ./git-master.zip
      cd git-master
      make configure
      ./configure --prefix=/usr/local
      make all
      make install
